### ISSUE TITLE
Update to vuetify 2.x

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-web#136]
Migrate from stylus to sass

**Comment by fnoop** [comment]
https://vuetifyjs.com/en/customization/sass-variables

**Comment by fnoop** [comment]
Major changes to vuetify2.  Default install is now alacarted with treeshaking, and webpack 4.
https://vuetifyjs.com/en/customization/a-la-carte

Start (another) new project and import the old one.

**Comment by fnoop** [comment]
https://github.com/vuetifyjs/vuetify/releases#user-content-upgrade-guide

**Comment by fnoop** [comment]
https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0

**Comment by fnoop** [comment]
Need to go through and convert all slot activators:
```
Regular activator
<!-- v1.5 -->

<v-dialog>
  <v-btn slot="activator">...</v-btn>
</v-dialog>
<!-- v2.0 -->

<v-dialog>
  <template v-slot:activator="{ on }"
    <v-btn v-on="on">...</v-btn>
  </template>
</v-dialog>
```

**Comment by fnoop** [comment]
Need to convert stylus mods:
```
// Import custom styles to override Vuetify defaults
// import '../stylus/main.styl'

// import 'vuetify/src/stylus/app.styl'
import colors from 'vuetify/es5/util/colors'
```

**Comment by fnoop** [comment]
Fix FAB

**Comment by fnoop** [comment]
Reopening, need to fix FAB

**Comment by fnoop** [comment]
https://vuetifyjs.com/en/components/floating-action-buttons#fab-with-speed-dial

**Comment by SamuelDudley** [comment]
@fnoop is this good to close?

**Comment by fnoop** [comment]
Yes!
