### ISSUE TITLE
update icons

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-web#157]
icons need to move to material design https://material.io/resources/icons/?icon=error_outline&style=outline

**Comment by fnoop** [comment]
Why do we need to move iconsets?

**Comment by SamuelDudley** [comment]
we don't... I think I tried to use the mdi icon assets in the past but there was an issue with an older version of vuetify.

**Comment by fnoop** [comment]
Ok great, it's a surprisingly difficult task choosing/setting icons, took me forever!  Not that I'm particularly attached to any of the ones there - feel free to find better ones of course - just didn't want to go through the process again unnecessarily..
