### ISSUE TITLE
To history or not to history, that is the question?

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-web#161]
If we want to set publicPath to '' or './' in vue.config.js, to allow relative pathing, then we can't use vue-router history mode:

https://cli.vuejs.org/config/#publicpath
https://router.vuejs.org/guide/essentials/history-mode.html

The difference is that we get 'prettier' URLs.  The difference is:
 http://maverick-ubuntuvm.local/web/maverick/video
vs
 http://maverick-ubuntuvm.local/web/maverick/#/video

**Comment by fnoop** [comment]
This allows us to have the -dist version running on any URL (eg. / or /web/maverick, or /maverick-web as in the github pages), so it's quite useful.

**Comment by SamuelDudley** [comment]
> This allows us to have the -dist version running on any URL (eg. / or /web/maverick, or /maverick-web as in the github pages), so it's quite useful.

I think the utility of this far outweighs the hashes in the urls
