### ISSUE TITLE
Maverick logo broken in Safari

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-web#175]
<img width="964" alt="Screenshot 2020-04-01 at 13 25 23" src="https://user-images.githubusercontent.com/8210968/78137304-f9f96980-741c-11ea-9937-9d39c97ad802.png">

**Comment by SamuelDudley** [comment]
Its actually broken in all my browsers... chrome, firefox, etc.. I'm assuming its an SVG and we are missing a font?

**Comment by fnoop** [comment]
Oh.  Duh.  Yes I need to convert the text to curves - I didn't notice because I have the fonts installed!
