### ISSUE TITLE
Refresh params if backend changes

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-web#34]
interface should do a full refresh of params if they change in the backend.  need to determine how to detect this - param count would be a simple, if crude way.

**Comment by SamuelDudley** [comment]
We could have the API maintain a control websocket that keeps the webui informed of the API state and delivers actions, such as `params stale, refresh` or similar.

**Comment by fnoop** [comment]
That's a great idea.

**Comment by fnoop** [comment]
This should be up to the API to notify the client of changes, which it already does.
