### ISSUE TITLE
Boolean parameters should be switch

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-web#38]
Dropdown select for boolean parameters is poor UX.  Switch would be better.

**Comment by fnoop** [comment]
Or boolean checkbox.

**Comment by SamuelDudley** [comment]
Call me simple but I get confused by a single checkbox that is labelled `enable`. I'm not saying this is what you were considering but I thought it was worth mentioning.
It needs to be __super__ clear what the state is currently and what is about to be saved. Hope that makes sense!

**Comment by fnoop** [comment]
I was thinking about a switch, like this:
https://vuetifyjs.com/en/components/selection-controls
I think they're nice and clear - they can turn a grey to indicate off or a green or other colour to indicate on, and can include text to that effect as well.  Nice ui feedback and great for touchscreens.

**Comment by SamuelDudley** [comment]
Looks good! One thought... I would like to see `Enabled` and `Disabled` rather than `True` and `False` for our application
