### ISSUE TITLE
Save / Cancel buttons are obscured by keyboard on small devices

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-web#40]
Open to comments on this one, but it would be great if we didn't have to scroll down to save the parameters on small devices. I personally would like to see save / cancel next to the input field in this scenario:  

![screenshot_20180304-134031](https://user-images.githubusercontent.com/8290680/36941933-ba7ed112-1fb6-11e8-9701-7c96e835ad63.png)

**Comment by SamuelDudley** [comment]
It may be possible to display the number only keyboard on mobile devices as well (but I think they are the same size).  Also seems the number keyboard has a range of issues: https://www.filamentgroup.com/lab/type-number.html

**Comment by fnoop** [comment]
Moved save and close buttons up to title row in https://github.com/goodrobots/maverick-web/commit/bdc9590f90c9bbeb9306fc8934bce62d87230f8a.
Also un-flattened save button for better ux.
