### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-web#9]
* themed or abstract?

**Comment by SamuelDudley** [comment]
Is this only for maverick-web or maverick in general?

Irrespective my vote is with abstract. Does anyone know a good and cheap graphic designer or are willing to have a go at designing the logo?

**Comment by fnoop** [comment]
I'm a terrible graphic designer but was going to have a go at this, at least for something temporary :)

**Comment by fnoop** [comment]
@SamuelDudley Any idea where we should keep the artwork for the logos?  As in the illustrator files, svgs etc?  I can add them just to the maverick-web repo somewhere that isn't actually used, just as storage, or we could add them to a separate repo somewhere?

**Comment by SamuelDudley** [comment]
We could have an asset repo at the goodrobots level and store them there. While I'm happy distributing the svg, jpg, etc perhaps the illustrator files should remain private?

**Comment by fnoop** [comment]
Do you mean a private repo for the illustrator files? I had presumed we would just distribute everything in the spirit of openness, but I guess you're right - perhaps the illustrator files should remain private in case someone else uses them to alter the logo.  The QGC design guidelines are quite good, we could follow them loosely just as a general guideline:
https://qgroundcontrol.gitbooks.io/design-guide/content/

**Comment by SamuelDudley** [comment]
Agreed, the QGC guidelines are nice. I just don't think we want to be publicly posting the illustrator files. The other formats, jpeg, PNG, whatever, go for it!
